spring.application.name=bookstore
# h2 tietokannan määritykset, konfiguraatiot 
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb

#näytä järjestelmän generoima SQL
#spring.jpa.show-sql=true

#API
#spring.data.rest.base-path=/api




spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#REST API
spring.data.rest.base-path=/api

#Port
server.port=8091

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/titust?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=titust
spring.datasource.password=password
spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=update

#HTTPS
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

server.ssl.key-store=/etc/ssl/private/springboot-example.p12
server.ssl.key-store-password=changeit